# -*- coding: utf-8 -*-
"""krys1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fby7jy5jW-4tlcOVZZGErGe7oOSx9HaX
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Ustawienie tytułu aplikacji Streamlit
st.title("🎅 Interaktywny Święty Mikołaj")
st.markdown("Kliknij przycisk poniżej, aby zmienić kolor stroju!")

# --- Obsługa Stanu ---
# Inicjalizacja stanu sesji dla koloru, jeśli jeszcze nie istnieje
if 'suit_color' not in st.session_state:
    st.session_state.suit_color = 'red'

def change_color():
    """Funkcja zmieniająca kolor stroju Mikołaja w stanie sesji."""
    if st.session_state.suit_color == 'red':
        st.session_state.suit_color = 'blue'
    else:
        st.session_state.suit_color = 'red'

# --- Funkcja Rysująca (Matplotlib) ---

def draw_santa(suit_color):
    """Rysuje postać Świętego Mikołaja na figurze Matplotlib."""
    fig, ax = plt.subplots(figsize=(8, 8))

    # Ustawienia osi
    ax.set_xlim(-10, 10)
    ax.set_ylim(-10, 10)
    ax.set_aspect('equal')
    ax.axis('off') # Ukrycie osi

    # --- Elementy Postaci ---

    # 1. Głowa (Jasna Skóra)
    head = patches.Circle((0, 4), 2.5, facecolor='#FCDAB9', edgecolor='black', linewidth=1)
    ax.add_patch(head)

    # 2. Tułów (Kolor Stroju)
    body = patches.Rectangle((-3, -5), 6, 8, facecolor=suit_color, edgecolor='black', linewidth=1)
    ax.add_patch(body)

    # 3. Czapka (Kolor Stroju)
    cap_tri = patches.Polygon([(-2.5, 6), (2.5, 6), (0.5, 8.5)], closed=True,
                              facecolor=suit_color, edgecolor='black', linewidth=1)
    ax.add_patch(cap_tri)

    # 4. Białe Ozdoby (Futerko)
    cap_fur = patches.Rectangle((-2.7, 5.5), 5.4, 0.7, facecolor='white', edgecolor='black', linewidth=1)
    ax.add_patch(cap_fur)
    pom_pom = patches.Circle((0.5, 8.5), 0.7, facecolor='white', edgecolor='black', linewidth=1)
    ax.add_patch(pom_pom)
    jacket_fur = patches.Rectangle((-3.2, -5.2), 6.4, 1, facecolor='white', edgecolor='black', linewidth=1)
    ax.add_patch(jacket_fur)

    # 5. Pas (Czarny)
    belt = patches.Rectangle((-3.5, -0.5), 7, 1, facecolor='black', edgecolor='black')
    ax.add_patch(belt)
    # Klamra Pasa (Żółta/Złota)
    buckle = patches.Rectangle((-1, 0), 2, 0.5, facecolor='gold', edgecolor='black', linewidth=1)
    ax.add_patch(buckle)

    # 6. Broda (Biała)
    beard = patches.Polygon([(-2.5, 3), (2.5, 3), (1, -1), (-1, -1)], closed=True,
                            facecolor='white', edgecolor='black', linewidth=1)
    ax.add_patch(beard)

    # 7. Oczy (Czarne)
    eye_left = patches.Circle((-1, 4.5), 0.3, facecolor='black')
    eye_right = patches.Circle((1, 4.5), 0.3, facecolor='black')
    ax.add_patch(eye_left)
    ax.add_patch(eye_right)

    # Dodanie tytułu informującego o interakcji
    ax.set_title(f"Aktualny strój: {suit_color.upper()}", fontsize=14, color='black')

    return fig

# --- Główna Logika Streamlit ---

# 1. Wyświetlenie przycisku interakcji
button_label = f"Przełącz na strój: {'Niebieski' if st.session_state.suit_color == 'red' else 'Czerwony'}"
st.button(button_label, on_click=change_color)

# 2. Rysowanie Mikołaja na podstawie aktualnego stanu
current_santa_fig = draw_santa(st.session_state.suit_color)

# 3. Wyświetlenie figury Matplotlib w Streamlit
st.pyplot(current_santa_fig)